spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start-only
  application:
    name: facilitator
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  session:
    timeout: 2h
    redis:
      flush-mode: IMMEDIATE # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    direct.reflect.facilitator: "debug"
