package direct.reflect.facilitator.dto;

public enum EventType {
    INIT, PARTICIPANT_JOINED, SESSION_STARTED, PHASE_CHANGED, NOTE_ADDED, NOTE_UPDATED, NOTE_DELETED, VOTING_STARTED, VOTING_ENDED, SESSION_ENDED
}
