/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/retros/{retroId}/steps/{stepId}/clusters/{clusterId}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["renameCluster"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/responses/{responseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a response
         * @description Updates the content of an existing participant response
         */
        put: operations["updateResponse"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a retrospective session
         * @description Creates a new retrospective session and registers the creator as facilitator
         */
        post: operations["createRetrospective"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/timer/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume the session timer
         * @description Resumes the countdown timer for the current step; facilitator-only action
         */
        post: operations["resumeTimer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/timer/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause the session timer
         * @description Pauses the countdown timer for the current step; facilitator-only action
         */
        post: operations["pauseTimer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/steps/{stepId}/responses/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal responses for a step
         * @description Makes all participant responses visible; facilitator-only action
         */
        post: operations["revealResponses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/steps/{stepId}/responses/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get rating responses for histogram
         * @description Returns all rating responses for the stage containing this step (used by HISTOGRAM_CHART component)
         */
        get: operations["getRatingResponses"];
        put?: never;
        /**
         * Submit a rating response
         * @description Submits a rating scale response for the current step
         */
        post: operations["submitRatingResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/steps/{stepId}/responses/column": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a column/categorical response
         * @description Submits a response to a multi-column board step
         */
        post: operations["submitColumnResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/steps/{stepId}/clusters/unmerge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unmerge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/steps/{stepId}/clusters/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["merge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a retrospective session
         * @description Transitions the session from LOBBY to active phase; facilitator-only action
         */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/responses/{responseId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle a vote on a response
         * @description Adds or removes a vote for the current participant on the specified response
         */
        post: operations["toggleVote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getParticipants"];
        put?: never;
        post: operations["joinRetrospective"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/escalations/{escalationId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggleVote_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance to the next step
         * @description Advances the retrospective to the next step; facilitator-only action
         */
        post: operations["nextStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActionItems"];
        put?: never;
        post: operations["createActionItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/actions/{actionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateActionItemStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/actions/{actionId}/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["escalateAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrganizations"];
        put?: never;
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeams"];
        put?: never;
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{orgId}/teams/{teamId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMembers"];
        put?: never;
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/actions/{actionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteActionItem"];
        options?: never;
        head?: never;
        patch: operations["updateActionItem"];
        trace?: never;
    };
    "/api/retros/{retroId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get retrospective state
         * @description Returns the current retrospective state for an active participant
         */
        get: operations["getRetroState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/timer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get timer state
         * @description Returns the timer state for the current step
         */
        get: operations["getTimerState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/steps/{stepId}/responses/rating/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user's rating response
         * @description Returns the authenticated user's rating response for a given step, or 404 if not yet submitted
         */
        get: operations["getMyRatingResponse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/steps/{stepId}/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRetroEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEscalations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retros/{retroId}/actions/previous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPreviousActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/retros/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["checkActiveSessions"];
        put?: never;
        post?: never;
        delete: operations["leaveActiveSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manager/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEscalations_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manager/escalations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEscalation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RenameClusterRequest: {
            name: string;
        };
        /** @description Result of updating a participant response */
        UpdateResponseResult: {
            /**
             * Format: uuid
             * @description ID of the updated response
             */
            responseId?: string;
            /** @description Updated content of the response */
            content?: string;
        };
        CreateRetroRequest: {
            sessionName: string;
        };
        CreateRetroResponse: {
            /** Format: uuid */
            retroId?: string;
            redirectUrl?: string;
            sessionName?: string;
        };
        /** @description Result of revealing responses for a step */
        RevealResult: {
            /**
             * Format: int64
             * @description ID of the step whose responses were revealed
             */
            stepId?: number;
            /** @description Always true — indicates reveal was successful */
            revealed?: boolean;
        };
        RatingResponseDto: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            rating: number;
            comment?: string;
            visible?: boolean;
            participantName?: string;
            /** Format: uuid */
            participantId?: string;
        };
        /** @description Result of submitting a participant response */
        SubmitResponseResult: {
            /**
             * Format: uuid
             * @description ID of the created/updated response
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            responseId?: string;
            /**
             * Format: int64
             * @description ID of the step the response belongs to
             * @example 1
             */
            stepId?: number;
        };
        ColumnResponseDto: {
            /** Format: uuid */
            id?: string;
            columnId: string;
            content: string;
            visible?: boolean;
            participantName?: string;
            /** Format: uuid */
            participantId?: string;
            /** Format: int32 */
            voteCount?: number;
            /** Format: uuid */
            clusterId?: string;
            clusterName?: string;
        };
        UnmergeRequest: {
            /** Format: uuid */
            responseId: string;
        };
        MergeRequest: {
            responseIds: string[];
        };
        /** @description Result of toggling a vote on a response */
        VoteResult: {
            /**
             * Format: uuid
             * @description ID of the response that was voted on
             */
            responseId?: string;
            /**
             * Format: int32
             * @description Updated total vote count for this response
             */
            voteCount?: number;
        };
        JoinRetroResponse: {
            /** Format: uuid */
            retroId?: string;
            redirectUrl?: string;
        };
        EscalationVoteResultDto: {
            /** Format: int64 */
            syncVersion?: number;
            /** Format: uuid */
            escalationId?: string;
            /** Format: int64 */
            voteCount?: number;
            /** Format: int32 */
            threshold?: number;
            thresholdMet?: boolean;
            voted?: boolean;
        };
        NextStepResult: {
            /** Format: uuid */
            retroId?: string;
            advanced?: boolean;
        };
        CreateActionItemRequest: {
            what: string;
            who: string;
            /** Format: date */
            dueDate: string;
            successCriteria?: string;
        };
        ActionItemDto: {
            /** Format: int64 */
            syncVersion?: number;
            /** Format: uuid */
            id?: string;
            what?: string;
            who?: string;
            /** Format: date */
            dueDate?: string;
            successCriteria?: string;
            escalated?: boolean;
            /** @enum {string} */
            status?: "OPEN" | "DONE";
            /** Format: uuid */
            createdByParticipantId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateActionItemStatusRequest: {
            /** @enum {string} */
            status: "OPEN" | "DONE";
        };
        EscalateActionRequest: {
            problemDescription: string;
        };
        EscalatedItemDto: {
            /** Format: int64 */
            syncVersion?: number;
            /** Format: uuid */
            id?: string;
            problemDescription?: string;
            /** Format: int64 */
            voteCount?: number;
            /** Format: int32 */
            threshold?: number;
            thresholdMet?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateOrganizationRequest: {
            name: string;
            slug: string;
        };
        OrganizationDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
        };
        CreateTeamRequest: {
            name: string;
        };
        TeamDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            organizationId?: string;
            name?: string;
        };
        AddMemberRequest: {
            /** Format: uuid */
            userId: string;
            /** @enum {string} */
            role: "MEMBER" | "MANAGER";
        };
        TeamMemberDto: {
            /** Format: uuid */
            teamId?: string;
            /** Format: uuid */
            userId?: string;
            /** @enum {string} */
            role?: "MEMBER" | "MANAGER";
        };
        UpdateActionItemRequest: {
            what?: string;
            who?: string;
            /** Format: date */
            dueDate?: string;
            successCriteria?: string;
        };
        AssistantMessageDto: {
            /** Format: uuid */
            retroId?: string;
            /** Format: int64 */
            stepId?: number;
            stepTitle?: string;
            publicText?: string;
        };
        AssistantStateDto: {
            current?: components["schemas"]["AssistantMessageDto"];
            history?: components["schemas"]["AssistantMessageDto"][];
            facilitatorCoachingNote?: string;
        };
        RetroStateDto: {
            /** Format: uuid */
            retroId?: string;
            /** Format: int64 */
            syncVersion?: number;
            phase?: string;
            /** Format: int64 */
            currentStepId?: number;
            /** Format: int32 */
            currentStepIndex?: number;
            steps?: components["schemas"]["StepSummaryDto"][];
            /** Format: uuid */
            facilitatorId?: string;
            isFacilitator?: boolean;
            /** Format: int32 */
            participantCount?: number;
            assistantState?: components["schemas"]["AssistantStateDto"];
        };
        StepSummaryDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            componentType?: string;
            advancementTrigger?: string;
            /** Format: int32 */
            durationSeconds?: number;
            componentConfig?: {
                [key: string]: unknown;
            };
            guidance?: string;
        };
        SyncVersionedResponseTimerStateDto: {
            /** Format: int64 */
            syncVersion?: number;
            data?: components["schemas"]["TimerStateDto"];
        };
        TimerStateDto: {
            /** Format: int64 */
            remainingSeconds?: number;
            isPaused?: boolean;
            state?: string;
        };
        ClusterGroupsDto: {
            clustered?: {
                [key: string]: components["schemas"]["ColumnResponseDto"][];
            };
            unclustered?: components["schemas"]["ColumnResponseDto"][];
        };
        ParticipantDto: {
            /** Format: uuid */
            participantId?: string;
            displayName?: string;
            role?: string;
        };
        SyncVersionedResponseListParticipantDto: {
            /** Format: int64 */
            syncVersion?: number;
            data?: components["schemas"]["ParticipantDto"][];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        SyncVersionedResponseListEscalatedItemDto: {
            /** Format: int64 */
            syncVersion?: number;
            data?: components["schemas"]["EscalatedItemDto"][];
        };
        SyncVersionedResponseListActionItemDto: {
            /** Format: int64 */
            syncVersion?: number;
            data?: components["schemas"]["ActionItemDto"][];
        };
        SessionInfo: {
            /** Format: uuid */
            sessionId?: string;
            sessionName?: string;
            role?: string;
        };
        LeaveActiveSessionsResult: {
            success?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    renameCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameClusterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateResponse: {
        parameters: {
            query: {
                content: string;
            };
            header?: never;
            path: {
                retroId: string;
                responseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UpdateResponseResult"];
                };
            };
            /** @description Not authorized to edit this response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UpdateResponseResult"];
                };
            };
        };
    };
    createRetrospective: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRetroRequest"];
            };
        };
        responses: {
            /** @description Session created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateRetroResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateRetroResponse"];
                };
            };
            /** @description Session could not be created */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateRetroResponse"];
                };
            };
        };
    };
    resumeTimer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timer resumed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only facilitators can resume the timer */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pauseTimer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timer paused successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only facilitators can pause the timer */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revealResponses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Responses revealed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevealResult"];
                };
            };
            /** @description Only facilitators can reveal responses */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevealResult"];
                };
            };
        };
    };
    getRatingResponses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rating responses returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RatingResponseDto"][];
                };
            };
            /** @description Participant is not part of this session */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RatingResponseDto"][];
                };
            };
        };
    };
    submitRatingResponse: {
        parameters: {
            query: {
                dto: components["schemas"]["RatingResponseDto"];
            };
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rating submitted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmitResponseResult"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmitResponseResult"];
                };
            };
        };
    };
    submitColumnResponse: {
        parameters: {
            query: {
                dto: components["schemas"]["ColumnResponseDto"];
            };
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response submitted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmitResponseResult"];
                };
            };
            /** @description Validation error or input limit exceeded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmitResponseResult"];
                };
            };
        };
    };
    unmerge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnmergeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    merge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session started successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only facilitators can start sessions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggleVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                responseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vote toggled successfully, returns updated vote count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoteResult"];
                };
            };
            /** @description Vote limit exceeded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoteResult"];
                };
            };
        };
    };
    getParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncVersionedResponseListParticipantDto"];
                };
            };
        };
    };
    joinRetrospective: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JoinRetroResponse"];
                };
            };
        };
    };
    toggleVote_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                escalationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EscalationVoteResultDto"];
                };
            };
        };
    };
    nextStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Advanced to the next step */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NextStepResult"];
                };
            };
            /** @description Only facilitators can advance the session */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NextStepResult"];
                };
            };
        };
    };
    getActionItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncVersionedResponseListActionItemDto"];
                };
            };
        };
    };
    createActionItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActionItemRequest"];
            };
        };
        responses: {
            /** @description Action item created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActionItemDto"];
                };
            };
        };
    };
    updateActionItemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                actionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActionItemStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActionItemDto"];
                };
            };
        };
    };
    escalateAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                actionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalateActionRequest"];
            };
        };
        responses: {
            /** @description Action escalated successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EscalatedItemDto"];
                };
            };
        };
    };
    getOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationDto"][];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Organization created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationDto"];
                };
            };
        };
    };
    getTeams: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamDto"][];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description Team created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamDto"];
                };
            };
        };
    };
    getMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamMemberDto"][];
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Team member added successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamMemberDto"];
                };
            };
        };
    };
    deleteActionItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                actionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Action item deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateActionItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                actionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActionItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActionItemDto"];
                };
            };
        };
    };
    getRetroState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrospective state returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RetroStateDto"];
                };
            };
            /** @description Participant is not part of this session */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RetroStateDto"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RetroStateDto"];
                };
            };
        };
    };
    getTimerState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timer state returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncVersionedResponseTimerStateDto"];
                };
            };
            /** @description Current step has no timer */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncVersionedResponseTimerStateDto"];
                };
            };
            /** @description Participant is not part of this session */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncVersionedResponseTimerStateDto"];
                };
            };
        };
    };
    getMyRatingResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rating response returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RatingResponseDto"];
                };
            };
            /** @description No rating response found for this participant and step */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RatingResponseDto"];
                };
            };
        };
    };
    getClusters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterGroupsDto"];
                };
            };
        };
    };
    getRetroEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    getEscalations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncVersionedResponseListEscalatedItemDto"];
                };
            };
        };
    };
    getPreviousActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActionItemDto"][];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    checkActiveSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    leaveActiveSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeaveActiveSessionsResult"];
                };
            };
        };
    };
    getEscalations_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EscalatedItemDto"][];
                };
            };
        };
    };
    getEscalation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EscalatedItemDto"];
                };
            };
        };
    };
}
