/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/retro/{retroId}/step/{stepId}/cluster/{clusterId}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["renameCluster"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/response/{responseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a response
         * @description Updates the content of an existing participant response
         */
        put: operations["updateResponse"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/timer/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume the session timer
         * @description Resumes the countdown timer for the current step; facilitator-only action
         */
        post: operations["resumeTimer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/timer/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause the session timer
         * @description Pauses the countdown timer for the current step; facilitator-only action
         */
        post: operations["pauseTimer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/step/{stepId}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal responses for a step
         * @description Makes all participant responses visible; facilitator-only action
         */
        post: operations["revealResponses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/step/{stepId}/response/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get rating responses for histogram
         * @description Returns all rating responses for the stage containing this step (used by HISTOGRAM_CHART component)
         */
        get: operations["getRatingResponses"];
        put?: never;
        /**
         * Submit a rating response
         * @description Submits a rating scale response for the current step
         */
        post: operations["submitRatingResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/step/{stepId}/response/column": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a column/categorical response
         * @description Submits a response to a multi-column board step
         */
        post: operations["submitColumnResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/step/{stepId}/cluster/unmerge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unmerge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/step/{stepId}/cluster/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["merge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a retrospective session
         * @description Transitions the session from LOBBY to active phase; facilitator-only action
         */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/response/{responseId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle a vote on a response
         * @description Adds or removes a vote for the current participant on the specified response
         */
        post: operations["toggleVote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["nextStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/leave-active-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveActiveSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinRetrospective"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRetrospective"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/timer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTimerState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/step/{stepId}/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRetroState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{retroId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRetroEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/check-active-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["checkActiveSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RenameClusterRequest: {
            name: string;
        };
        /** @description Result of updating a participant response */
        UpdateResponseResult: {
            /**
             * Format: uuid
             * @description ID of the updated response
             */
            responseId?: string;
            /** @description Updated content of the response */
            content?: string;
        };
        /** @description Result of revealing responses for a step */
        RevealResult: {
            /**
             * Format: int64
             * @description ID of the step whose responses were revealed
             */
            stepId?: number;
            /** @description Always true — indicates reveal was successful */
            revealed?: boolean;
        };
        RatingResponseDto: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            rating: number;
            comment?: string;
            visible?: boolean;
            participantName?: string;
            /** Format: uuid */
            participantId?: string;
        };
        /** @description Result of submitting a participant response */
        SubmitResponseResult: {
            /**
             * Format: uuid
             * @description ID of the created/updated response
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            responseId?: string;
            /**
             * Format: int64
             * @description ID of the step the response belongs to
             * @example 1
             */
            stepId?: number;
        };
        ColumnResponseDto: {
            /** Format: uuid */
            id?: string;
            columnId: string;
            content: string;
            visible?: boolean;
            participantName?: string;
            /** Format: uuid */
            participantId?: string;
            /** Format: int32 */
            voteCount?: number;
            /** Format: uuid */
            clusterId?: string;
            clusterName?: string;
        };
        UnmergeRequest: {
            /** Format: uuid */
            responseId: string;
        };
        MergeRequest: {
            responseIds: string[];
        };
        /** @description Result of toggling a vote on a response */
        VoteResult: {
            /**
             * Format: uuid
             * @description ID of the response that was voted on
             */
            responseId?: string;
            /**
             * Format: int32
             * @description Updated total vote count for this response
             */
            voteCount?: number;
        };
        JoinRetroRequest: {
            retroId: string;
        };
        CreateRetroRequest: {
            sessionName: string;
        };
        TimerStateDto: {
            /** Format: int64 */
            remainingSeconds?: number;
            isPaused?: boolean;
            state?: string;
        };
        ClusterGroupsDto: {
            clustered?: {
                [key: string]: components["schemas"]["ColumnResponseDto"][];
            };
            unclustered?: components["schemas"]["ColumnResponseDto"][];
        };
        AssistantMessageDto: {
            /** Format: uuid */
            retroId?: string;
            /** Format: int64 */
            stepId?: number;
            stepTitle?: string;
            publicText?: string;
        };
        AssistantStateDto: {
            current?: components["schemas"]["AssistantMessageDto"] | null;
            history?: components["schemas"]["AssistantMessageDto"][];
            facilitatorCoachingNote?: string | null;
        };
        RetroStateDto: {
            /** Format: uuid */
            retroId?: string;
            phase?: string;
            /** Format: int64 */
            currentStepId?: number;
            /** Format: int32 */
            currentStepIndex?: number;
            steps?: components["schemas"]["StepSummaryDto"][];
            /** Format: uuid */
            facilitatorId?: string;
            isFacilitator?: boolean;
            /** Format: int32 */
            participantCount?: number;
            assistantState?: components["schemas"]["AssistantStateDto"] | null;
        };
        StepSummaryDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            componentType?: string;
            advancementTrigger?: string;
            /** Format: int32 */
            durationSeconds?: number;
            componentConfig?: {
                [key: string]: unknown;
            };
            guidance?: string;
        };
        ParticipantDto: {
            /** Format: uuid */
            participantId?: string;
            displayName?: string;
            role?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        SessionInfo: {
            /** Format: uuid */
            sessionId?: string;
            sessionName?: string;
            role?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    renameCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameClusterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateResponse: {
        parameters: {
            query: {
                content: string;
            };
            header?: never;
            path: {
                retroId: string;
                responseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UpdateResponseResult"];
                };
            };
            /** @description Not authorized to edit this response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UpdateResponseResult"];
                };
            };
        };
    };
    resumeTimer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timer resumed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only facilitators can resume the timer */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pauseTimer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timer paused successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only facilitators can pause the timer */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revealResponses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Responses revealed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevealResult"];
                };
            };
            /** @description Only facilitators can reveal responses */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevealResult"];
                };
            };
        };
    };
    getRatingResponses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rating responses returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RatingResponseDto"][];
                };
            };
        };
    };
    submitRatingResponse: {
        parameters: {
            query: {
                dto: components["schemas"]["RatingResponseDto"];
            };
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rating submitted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmitResponseResult"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmitResponseResult"];
                };
            };
        };
    };
    submitColumnResponse: {
        parameters: {
            query: {
                dto: components["schemas"]["ColumnResponseDto"];
            };
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response submitted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmitResponseResult"];
                };
            };
            /** @description Validation error or input limit exceeded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmitResponseResult"];
                };
            };
        };
    };
    unmerge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnmergeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    merge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session started successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only facilitators can start sessions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggleVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                responseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vote toggled successfully, returns updated vote count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoteResult"];
                };
            };
            /** @description Vote limit exceeded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoteResult"];
                };
            };
        };
    };
    nextStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    leaveActiveSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    joinRetrospective: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRetroRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createRetrospective: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRetroRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTimerState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TimerStateDto"];
                };
            };
        };
    };
    getClusters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
                stepId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterGroupsDto"];
                };
            };
        };
    };
    getRetroState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RetroStateDto"];
                };
            };
        };
    };
    getParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipantDto"][];
                };
            };
        };
    };
    getRetroEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                retroId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    checkActiveSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
}
