package direct.reflect.facilitator.facilitation;

import java.time.LocalDateTime;
import java.util.UUID;
import jakarta.persistence.*;
import lombok.Data;
import direct.reflect.facilitator.facilitation.ParticipantRole;

@Entity
@Table(name = "participants")
@IdClass(ParticipantId.class) // Specify the composite key class
@Data
public class Participant {
    /**
     * Stable identifier (UUID) for the user. Part of the composite primary key.
     * This ID can be repeated across different participation records if the same user joins multiple sessions.
     * This will be a time-ordered (v7-like) UUID, typically generated by the service.
     */
    @Id // Part of composite PK
    @Column(name = "participant_id", nullable = false)
    private UUID participantId;
    
    /**
     * The session this participation record belongs to. Part of the composite primary key.
     */
    @Id // Part of composite PK
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "session_id", referencedColumnName = "id", nullable = false)
    private RetroSession session;

    /**
     * Username for authentication purposes, associated with the stable participantId.
     * Can be null for anonymous users.
     */
    @Column(name = "username")
    private String username;
    
    /**
     * User-selected display name for this specific session participation.
     */
    @Column(name = "display_name", nullable = false)
    private String displayName;
    
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false) // Role should be non-nullable for a participation
    private ParticipantRole role;
    
    /**
     * Last seen timestamp for the user in this specific session.
     */
    @Column(name = "last_seen")
    private LocalDateTime lastSeen;
    
    /**
     * Custom toString to avoid LazyInitializationException.
     */
    @Override
    public String toString() {
        String sessionInfo = "session=" + (session != null ? session.getId() : "null");
        return "Participant{" +
            "participantId=" + participantId +
            ", " + sessionInfo +
            ", username='" + username + '\'' +
            ", displayName='" + displayName + '\'' +
            ", role=" + role +
            ", lastSeen=" + lastSeen +
            '}';
    }
}
