/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Payload for PARTICIPANT_JOINED and PARTICIPANT_LEFT SSE events. A plain string (participant display name). Semantically equivalent to participant-event.schema.json; both are kept for naming-compatibility with the plan schema set.
 */
export type ParticipantName = string;
