/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Payload for PHASE_STARTED SSE events. A plain string representing the retro phase name (e.g. GATHER_DATA, GENERATE_INSIGHTS). Maps to the RetroPhase enum string value.
 */
export type PhaseName = string;
