/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Payload for NOTE_ADDED and NOTE_UPDATED (single response) SSE events. Maps to RetroEvent.ResponseData Java record.
 */
export interface ResponseData {
  /**
   * UUID of the participant response
   */
  responseId: string;
  /**
   * ID of the retro step this response belongs to
   */
  stepId: number;
  /**
   * UUID of the participant who submitted the response
   */
  participantId: string;
  /**
   * Display name of the participant
   */
  participantName: string;
  /**
   * Short summary of the response content for display
   */
  displaySummary: string;
  /**
   * Whether the response is visible to all participants
   */
  isVisible: boolean;
  /**
   * ISO 8601 timestamp when the response was submitted
   */
  submittedAt: string;
}
