/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Top-level SSE event wrapper. Maps to RetroEvent Java record. The payload field varies by event type.
 */
export interface RetroEventEnvelope {
  /**
   * Unique event ID, format: evt-xxxxxxxx
   */
  correlationId: string;
  /**
   * UUID of the retro session
   */
  retroId: string;
  /**
   * SSE event type name (matches RetroEvent.EventType enum)
   */
  type:
    | "PARTICIPANT_JOINED"
    | "PARTICIPANT_LEFT"
    | "SESSION_STARTED"
    | "STEP_ADVANCED"
    | "RETRO_CREATED"
    | "PHASE_STARTED"
    | "NOTE_ADDED"
    | "NOTE_UPDATED"
    | "NOTE_DELETED"
    | "VOTE_ADDED"
    | "VOTE_REMOVED"
    | "GROUP_CREATED"
    | "GROUP_UPDATED"
    | "GROUP_DELETED"
    | "ACTION_CREATED"
    | "ACTION_UPDATED"
    | "ACTION_DELETED"
    | "TIMER_STARTED"
    | "TIMER_PAUSED"
    | "TIMER_FINISHED";
  /**
   * ID of the entity that triggered this event (participant ID or 'system')
   */
  sourceId: string;
  /**
   * ISO 8601 timestamp when the event was created
   */
  timestamp: string;
  /**
   * Event-specific payload. Type depends on event type. Null for void events.
   */
  payload?: {
    [k: string]: unknown;
  };
}
