/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Payload for NOTE_UPDATED (batch reveal) SSE events. A plain integer representing the stepId when all notes in a step are revealed at once (responsesRevealed factory method).
 */
export type StepId = number;
