/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Payload for void SSE events (SESSION_STARTED, STEP_ADVANCED, RETRO_CREATED, TIMER_STARTED, TIMER_PAUSED, TIMER_FINISHED). The payload field will be null/absent in the envelope.
 */
export type VoidEvent = null;
